// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type ApiKey struct {
	ID      int32  `json:"id"`
	Key     string `json:"key"`
	Owner   int32  `json:"owner"`
	Enabled bool   `json:"enabled"`
	Hits    int32  `json:"hits"`
	Errors  int32  `json:"errors"`
}

type Storage struct {
	ID        int32  `json:"id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	Available bool   `json:"available"`
	CreatedBy int32  `json:"created_by"`
	Downloads int32  `json:"downloads"`
	Errors    int32  `json:"errors"`
}

type User struct {
	ID int32 `json:"id"`
	// username
	Username string `json:"username"`
	// Name of the User
	Name string `json:"name"`
}
